---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: twininterfaces.dtd.ktwin
spec:
  group: dtd.ktwin
  names:
    kind: TwinInterface
    listKind: TwinInterfaceList
    plural: twininterfaces
    singular: twininterface
  scope: Namespaced
  versions:
  - name: v0
    schema:
      openAPIV3Schema:
        description: TwinInterface is the Schema for the twininterfaces API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TwinInterfaceSpec defines the desired state of TwinInterface
            properties:
              commands:
                items:
                  properties:
                    commandType:
                      type: string
                    comment:
                      type: string
                    description:
                      type: string
                    displayName:
                      type: string
                    id:
                      type: string
                    name:
                      type: string
                    request:
                      properties:
                        description:
                          type: string
                        displayName:
                          type: string
                        name:
                          type: string
                        schema:
                          properties:
                            enumType:
                              properties:
                                enumValues:
                                  items:
                                    properties:
                                      displayName:
                                        type: string
                                      enumValue:
                                        type: string
                                      name:
                                        type: string
                                    type: object
                                  type: array
                                valueSchema:
                                  type: string
                              type: object
                            primitiveType:
                              type: string
                          type: object
                      type: object
                    response:
                      properties:
                        description:
                          type: string
                        displayName:
                          type: string
                        name:
                          type: string
                        schema:
                          properties:
                            enumType:
                              properties:
                                enumValues:
                                  items:
                                    properties:
                                      displayName:
                                        type: string
                                      enumValue:
                                        type: string
                                      name:
                                        type: string
                                    type: object
                                  type: array
                                valueSchema:
                                  type: string
                              type: object
                            primitiveType:
                              type: string
                          type: object
                      type: object
                  required:
                  - request
                  - response
                  type: object
                type: array
              comment:
                type: string
              description:
                type: string
              displayName:
                type: string
              extends:
                properties:
                  id:
                    type: string
                type: object
              id:
                type: string
              properties:
                items:
                  properties:
                    comment:
                      type: string
                    description:
                      type: string
                    displayName:
                      type: string
                    id:
                      type: string
                    name:
                      type: string
                    schema:
                      properties:
                        enumType:
                          properties:
                            enumValues:
                              items:
                                properties:
                                  displayName:
                                    type: string
                                  enumValue:
                                    type: string
                                  name:
                                    type: string
                                type: object
                              type: array
                            valueSchema:
                              type: string
                          type: object
                        primitiveType:
                          type: string
                      type: object
                    writable:
                      type: boolean
                  type: object
                type: array
              relationships:
                items:
                  properties:
                    comment:
                      type: string
                    description:
                      type: string
                    displayName:
                      type: string
                    id:
                      type: string
                    maxMultiplicity:
                      type: integer
                    minMultiplicity:
                      type: integer
                    name:
                      type: string
                    properties:
                      items:
                        properties:
                          comment:
                            type: string
                          description:
                            type: string
                          displayName:
                            type: string
                          id:
                            type: string
                          name:
                            type: string
                          schema:
                            properties:
                              enumType:
                                properties:
                                  enumValues:
                                    items:
                                      properties:
                                        displayName:
                                          type: string
                                        enumValue:
                                          type: string
                                        name:
                                          type: string
                                      type: object
                                    type: array
                                  valueSchema:
                                    type: string
                                type: object
                              primitiveType:
                                type: string
                            type: object
                          writable:
                            type: boolean
                        type: object
                      type: array
                    schema:
                      properties:
                        enumType:
                          properties:
                            enumValues:
                              items:
                                properties:
                                  displayName:
                                    type: string
                                  enumValue:
                                    type: string
                                  name:
                                    type: string
                                type: object
                              type: array
                            valueSchema:
                              type: string
                          type: object
                        primitiveType:
                          type: string
                      type: object
                    target:
                      type: string
                    writeable:
                      type: boolean
                  type: object
                type: array
              telemetries:
                items:
                  properties:
                    comment:
                      type: string
                    description:
                      type: string
                    displayName:
                      type: string
                    id:
                      type: string
                    name:
                      type: string
                    schema:
                      properties:
                        enumType:
                          properties:
                            enumValues:
                              items:
                                properties:
                                  displayName:
                                    type: string
                                  enumValue:
                                    type: string
                                  name:
                                    type: string
                                type: object
                              type: array
                            valueSchema:
                              type: string
                          type: object
                        primitiveType:
                          type: string
                      type: object
                  type: object
                type: array
            required:
            - extends
            type: object
          status:
            description: TwinInterfaceStatus defines the observed state of TwinInterface
            properties:
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
